const {test}=require('node:test');
const assert=require('node:assert/strict');
const {validateSnapshot,projectSnapshot,readChatgptAds}=require('../src/chatgpt-ads');
const {createChannelService}=require('../src/channels');
const now=Date.parse('2026-09-15T18:00:00Z');
const window={start:'2026-09-08T00:00:00Z',end:'2026-09-15T00:00:00Z'};
function fixture() { return {version:1,importedAt:new Date(now).toISOString(),account:{id:'adacct_6a7209ea372c81a29343ecb7e4b20276',name:'Project Win LLC',currency:'USD'},campaigns:[{id:'campaign',name:'Example',status:'paused'}],report:{has_more:false,data:Array.from({length:7},(_,i)=>{const date=`2026-09-${String(i+8).padStart(2,'0')}`;return {campaign_id:'campaign',readable_time:date,start_time:Date.parse(date+'T04:00:00Z')/1000,end_time:Date.parse(date+'T04:00:00Z')/1000+86400,impressions:0,clicks:0,spend:0};})}}; }
test('explicit reported zeros remain zero; empty ratios stay unknown',()=>{const r=projectSnapshot(fixture(),window,now);assert.equal(r.data.impressions,0);assert.equal(r.data.cpc,null);assert.equal(r.data.ctr,null);assert.equal(r.data.partial,false);assert.equal(r.data.reportedDays,7);});
test('filter uses provider reporting dates without shifting 04:00 boundaries into UTC days',()=>{const s=fixture();s.report.data[6].clicks=2;s.report.data[6].impressions=100;s.report.data[6].spend=4.99;const r=projectSnapshot(s,{start:'2026-09-14T00:00:00Z',end:'2026-09-15T00:00:00Z'},now);assert.equal(r.data.clicks,2);assert.equal(r.data.spend,4.99);assert.equal(r.data.reportedDays,1);assert.match(r.timeBasis,/separate from UTC/);});
test('missing dates, stale snapshots, and Today never masquerade as full current coverage',()=>{const s=fixture();s.report.data.pop();const r=projectSnapshot(s,window,now+2*86400000);assert.equal(r.stale,true);assert.equal(r.data.partial,true);assert.equal(r.data.through,'2026-09-13');assert.equal(projectSnapshot(s,{...window,partialDay:true},now).data,null);assert.equal(projectSnapshot(s,{start:'2026-08-01',end:'2026-08-08'},now).status,'not_collected');});
test('reject wrong accounts, currency, pagination, duplicates and malformed metrics',()=>{for(const mutate of [s=>s.account.id='other',s=>s.account.currency='EUR',s=>s.report.has_more=true,s=>s.report.data.push(s.report.data[0]),s=>s.report.data[0].spend=null,s=>s.report.data[0].clicks=-1,s=>s.report.data[0].readable_time='2026-02-31',s=>s.report.data[0].campaign_id='unclassified']){const s=fixture();mutate(s);assert.throws(()=>validateSnapshot(s));}});
test('a missing campaign day is not promoted into an all-campaign total',()=>{const s=fixture();s.campaigns.push({id:'missing',name:'Other'});assert.equal(projectSnapshot(s,window,now).data,null);});
test('file failures return unknown and never leak errors',async()=>{const r=await readChatgptAds(window,{readFile:async()=>{throw Error('private detail')}});assert.equal(r.data,null);assert.ok(!JSON.stringify(r).includes('private detail'));});
test('new imports are visible even when the Instagram response is cached',async()=>{let s=fixture();const service=createChannelService({now:()=>now,readFile:async file=>{if(file.endsWith('chatgpt-ads.json')) return JSON.stringify(s);throw Error('No Instagram');}});assert.equal((await service(window)).chatgpt.data.clicks,0);s.report.data[0].clicks=3;assert.equal((await service(window)).chatgpt.data.clicks,3);});
